[2025-06-18 16:53:33,075] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: agile_data_science_batch_prediction_model_training.pyspark_train_classifier_model 2025-06-18T16:53:32.083450+00:00 [queued]>
[2025-06-18 16:53:33,088] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: agile_data_science_batch_prediction_model_training.pyspark_train_classifier_model 2025-06-18T16:53:32.083450+00:00 [queued]>
[2025-06-18 16:53:33,089] {taskinstance.py:1095} INFO - 
--------------------------------------------------------------------------------
[2025-06-18 16:53:33,089] {taskinstance.py:1096} INFO - Starting attempt 1 of 4
[2025-06-18 16:53:33,089] {taskinstance.py:1097} INFO - 
--------------------------------------------------------------------------------
[2025-06-18 16:53:33,096] {taskinstance.py:1115} INFO - Executing <Task(BashOperator): pyspark_train_classifier_model> on 2025-06-18T16:53:32.083450+00:00
[2025-06-18 16:53:33,098] {standard_task_runner.py:52} INFO - Started process 257 to run task
[2025-06-18 16:53:33,103] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'agile_data_science_batch_prediction_model_training', 'pyspark_train_classifier_model', '2025-06-18T16:53:32.083450+00:00', '--job-id', '3', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/setup.py', '--cfg-path', '/tmp/tmp0kysxm1u', '--error-file', '/tmp/tmp0k1loylb']
[2025-06-18 16:53:33,107] {standard_task_runner.py:77} INFO - Job 3: Subtask pyspark_train_classifier_model
[2025-06-18 16:53:33,149] {logging_mixin.py:109} INFO - Running <TaskInstance: agile_data_science_batch_prediction_model_training.pyspark_train_classifier_model 2025-06-18T16:53:32.083450+00:00 [running]> on host f1d39cfd16a0
[2025-06-18 16:53:33,213] {taskinstance.py:1254} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=agile_data_science_batch_prediction_model_training
AIRFLOW_CTX_TASK_ID=pyspark_train_classifier_model
AIRFLOW_CTX_EXECUTION_DATE=2025-06-18T16:53:32.083450+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-06-18T16:53:32.083450+00:00
[2025-06-18 16:53:33,213] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2025-06-18 16:53:33,214] {subprocess.py:63} INFO - Running command: ['bash', '-c', '\necho "Base Path: /opt/***/practica_creativa";\necho "Full File Path: /opt/***/practica_creativa/resources/train_spark_mllib_model.py";\nspark-submit --master local[8]   /opt/***/practica_creativa/resources/train_spark_mllib_model.py   /opt/***/practica_creativa']
[2025-06-18 16:53:33,222] {subprocess.py:74} INFO - Output:
[2025-06-18 16:53:33,228] {subprocess.py:78} INFO - Base Path: /opt/***/practica_creativa
[2025-06-18 16:53:33,228] {subprocess.py:78} INFO - Full File Path: /opt/***/practica_creativa/resources/train_spark_mllib_model.py
[2025-06-18 16:53:35,581] {subprocess.py:78} INFO - WARNING: An illegal reflective access operation has occurred
[2025-06-18 16:53:35,581] {subprocess.py:78} INFO - WARNING: Illegal reflective access by org.apache.spark.unsafe.Platform (file:/opt/spark-3.0.0-bin-hadoop3.2/jars/spark-unsafe_2.12-3.0.0.jar) to constructor java.nio.DirectByteBuffer(long,int)
[2025-06-18 16:53:35,582] {subprocess.py:78} INFO - WARNING: Please consider reporting this to the maintainers of org.apache.spark.unsafe.Platform
[2025-06-18 16:53:35,582] {subprocess.py:78} INFO - WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
[2025-06-18 16:53:35,582] {subprocess.py:78} INFO - WARNING: All illegal access operations will be denied in a future release
[2025-06-18 16:53:36,246] {subprocess.py:78} INFO - 25/06/18 16:53:36 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-06-18 16:53:36,706] {subprocess.py:78} INFO - python: can't open file '/opt/***/practica_creativa/resources/train_spark_mllib_model.py': [Errno 2] No such file or directory
[2025-06-18 16:53:36,717] {subprocess.py:78} INFO - log4j:WARN No appenders could be found for logger (org.apache.spark.util.ShutdownHookManager).
[2025-06-18 16:53:36,718] {subprocess.py:78} INFO - log4j:WARN Please initialize the log4j system properly.
[2025-06-18 16:53:36,718] {subprocess.py:78} INFO - log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
[2025-06-18 16:53:36,766] {subprocess.py:82} INFO - Command exited with return code 2
[2025-06-18 16:53:36,781] {taskinstance.py:1463} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1165, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1283, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1313, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/bash.py", line 176, in execute
    raise AirflowException('Bash command failed. The command returned a non-zero exit code.')
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code.
[2025-06-18 16:53:36,788] {taskinstance.py:1513} INFO - Marking task as UP_FOR_RETRY. dag_id=agile_data_science_batch_prediction_model_training, task_id=pyspark_train_classifier_model, execution_date=20250618T165332, start_date=20250618T165333, end_date=20250618T165336
[2025-06-18 16:53:36,821] {local_task_job.py:151} INFO - Task exited with return code 1
[2025-06-18 16:53:36,855] {local_task_job.py:261} INFO - 0 downstream tasks scheduled from follow-on schedule check
